### ISSUE TITLE
Do not repeat notifications

### ISSUE THREAD

**Issue by baterflyrity** [epidemicz/FreeGameNotifications#1]
Hi!

Nice addon. Unfortunately, shows same notifications on each restart.
Also notification can not be dismissed any ways until store opened.

All in all great idea with currently unusable spam.

**Comment by xboxhaxorz** [comment]
It actually shows me the notification multiple times, if i play a game for say 2 hrs and then stop, the notification is there again

The dismiss all button also doesnt work so if there are multiple games you have to click the x for each

**Comment by Rings4** [comment]
+1. I'm not sure if you're required to sign in to Epic games for it to be able to tell if you've gotten a game, but that shouldn't be necessary either way, and it's something I'm not willing to do. 

I simply want to dismiss a notification manually and never have that same notification pop up again.

**Comment by AlexeSimon** [comment]
Hello, 
Thank you for this great add-on.
I have the same issue and request.

Should be easy enough to solve with a notification history.

**Comment by AlexeSimon** [comment]
I took the time to solve it in 
#2 

Please pull, test, and make a new release for everyone to have this fixed.

(I made a release on my [fork](https://github.com/AlexeSimon/FreeGameNotificationsHistory/tree/master) as well if anyone is interested. Just download and run the [.pext](https://github.com/AlexeSimon/FreeGameNotificationsHistory/releases/tag/Latest) to update the add-on)

**Comment by baterflyrity** [comment]
@AlexeSimon , very nice, thanks! Hope devs will merge it in a while.

**Comment by matt-buckley** [comment]
+1 on this issue. It seems perhaps only @epidemicz has write permissions to this repo.

**Comment by epidemicz** [comment]
Hey @matt-buckley thanks for the ping and thanks very much @AlexeSimon for the PR. I will be able to look closer tonight and test but looks good so far and will merge in asap.

Sorry I didn't see this sooner, my GitHub notifications are a little wonky.

**Comment by AlexeSimon** [comment]
Just in time to not have your plugin high jacked by Crow for inactivity!
Apart from a quick review, maybe some testing and putting back your git url in extension.yaml, it should be good to go.

**Comment by epidemicz** [comment]
Thanks everyone for taking the time to report this and add feedback. And especially thanks to @AlexeSimon for doing the work. 

You should see version 1.1.1 available now.
